-- Contrôle de version mobile (Android / iOS) — lecture publique des lignes actives.

CREATE TABLE IF NOT EXISTS public.app_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform text NOT NULL CHECK (platform IN ('android', 'ios')),
  latest_version text NOT NULL,
  min_supported_version text NOT NULL,
  store_url text,
  message text,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS app_versions_platform_active_idx
  ON public.app_versions (platform, is_active);

ALTER TABLE public.app_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read active app versions" ON public.app_versions;
CREATE POLICY "Public can read active app versions"
  ON public.app_versions
  FOR SELECT
  USING (is_active = true);

-- Politique prod : bloquer les versions < 4.0.0 (min_supported_version).
-- latest_version alignée sur app.json (4.2.0 au moment de la migration).
UPDATE public.app_versions
SET is_active = false, updated_at = now()
WHERE platform IN ('ios', 'android') AND is_active = true;

INSERT INTO public.app_versions (
  platform,
  latest_version,
  min_supported_version,
  store_url,
  message,
  is_active
) VALUES
(
  'ios',
  '4.2.0',
  '4.0.0',
  'https://apps.apple.com/app/idVOTRE_APP_IOS',
  NULL,
  true
),
(
  'android',
  '4.2.0',
  '4.0.0',
  'https://play.google.com/store/apps/details?id=com.youmbia.mobile',
  NULL,
  true
);
